
import java.util.ArrayList;
import javax.swing.JComboBox;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author NICU
 */
public class jfrmJovenSaludable extends javax.swing.JFrame {
    // Lista donde se almacenarán todos los alimentos del archivo CSV
    private ArrayList<Alimento> listaAlimentos = new ArrayList<>();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(jfrmJovenSaludable.class.getName());

    /**
     * Creates new form jfrmJovenSaludable
     */
    public jfrmJovenSaludable() {
        initComponents();
        this.setLocationRelativeTo(null);//localizacion
        this.setTitle("Joven Saludable");//Titulo
        
        
        // Crear un objeto para leer el archivo CSV
// Crear un objeto para leer el archivo CSV
        LeerCSV lector = new LeerCSV();

        // Guardar todos los alimentos en la lista
        listaAlimentos = lector.leerArchivoCSV();

        // Llenar los ComboBox
        cargarCombos();
        

    }

    /*
     * Método encargado de llenar todos los JComboBox.
     */
    private void cargarCombos() {
        // DESAYUNO
    llenarCombo(cmbProteinaDesayuno, "Desayuno", "Proteína");
    llenarCombo(cmbCarbohidratoDesayuno, "Desayuno", "Carbohidrato");
    llenarCombo(cmbGrasaDesayuno, "Desayuno", "Grasa");
    llenarCombo(cmbFrutaDesayuno, "Desayuno", "Fruta");
    llenarCombo(cmbBebidaDesayuno, "Desayuno", "Bebida");

    // ALMUERZO
    llenarCombo(cmbProteinaAlmuerzo, "Almuerzo", "Proteína");
    llenarCombo(cmbCarbohidratoAlmuerzo, "Almuerzo", "Carbohidrato");
    llenarCombo(cmbGrasaAlmuerzo, "Almuerzo", "Grasa");
    llenarCombo(cmbFrutaAlmuerzo, "Almuerzo", "Fruta");
    llenarCombo(cmbBebidaAlmuerzo, "Almuerzo", "Bebida");

    // CENA
    llenarCombo(cmbProteinaCena, "Cena", "Proteína");
    llenarCombo(cmbCarbohidratoCena, "Cena", "Carbohidrato");
    llenarCombo(cmbGrasaCena, "Cena", "Grasa");
    llenarCombo(cmbFrutaCena, "Cena", "Fruta");
    llenarCombo(cmbBebidaCena, "Cena", "Bebida");

    }
    /*
     * Llena un JComboBox con los alimentos del tiempo de comida
     * y tipo que se indiquen.
     */
    private void llenarCombo(JComboBox<String> combo,
                             String tiempo,
                             String tipo) {

        // Elimina todos los elementos del ComboBox
        combo.removeAllItems();

        // Recorrer la lista de alimentos
        for (Alimento alimento : listaAlimentos) {

            // Verificar si corresponde al tiempo y tipo solicitados
            if (alimento.getTiempoComida().equalsIgnoreCase(tiempo)
                    && alimento.getTipo().equalsIgnoreCase(tipo)) {

                // Agregar el nombre del alimento al ComboBox
                combo.addItem(alimento.getNombre());

            }

        }

    }
    /*
 * Busca las calorías de un alimento según su nombre.
 */
private int buscarCalorias(String nombreAlimento) {

    // Recorrer la lista de alimentos
    for (Alimento alimento : listaAlimentos) {

        // Si encuentra el alimento
        if (alimento.getNombre().equalsIgnoreCase(nombreAlimento)) {

            // Devuelve las calorías
            return alimento.getCalorias();

        }

    }

    // Si no encuentra el alimento
    return 0;

}
private int calcularCalorias(String alimento, String cantidadTexto) {

    int calorias = buscarCalorias(alimento);

    int cantidad;

    try {
        cantidad = Integer.parseInt(cantidadTexto);
    } catch (NumberFormatException e) {
        cantidad = 0;
    }

    return calorias * cantidad;

}
private int obtenerCantidad(String texto) {

    try {
        return Integer.parseInt(texto);
    } catch (NumberFormatException e) {
        return 0;
    }

}

/*
 * Muestra en un JTextField las calorías del alimento seleccionado.
 */
private void actualizarCalorias(JComboBox<String> combo,
                                javax.swing.JTextField txtCalorias) {

    // Verificar que exista un elemento seleccionado
    if (combo.getSelectedItem() == null) {

        txtCalorias.setText("");

        return;

    }

    // Obtener el nombre del alimento seleccionado
    String nombreAlimento = combo.getSelectedItem().toString();

    // Buscar las calorías
    int calorias = buscarCalorias(nombreAlimento);

    // Mostrar las calorías
    txtCalorias.setText(String.valueOf(calorias));

}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblMetaCalorias = new javax.swing.JLabel();
        pnlDesayuno = new javax.swing.JPanel();
        lblDesayuno = new javax.swing.JLabel();
        lblProteinaDesayuno = new javax.swing.JLabel();
        cmbProteinaDesayuno = new javax.swing.JComboBox<>();
        lblAlimento = new javax.swing.JLabel();
        lblCalorias = new javax.swing.JLabel();
        lblCantidad = new javax.swing.JLabel();
        txtCaloriasProteinaDesayuno = new javax.swing.JTextField();
        txtCantidadProteinaDesayuno = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbCarbohidratoDesayuno = new javax.swing.JComboBox<>();
        cmbGrasaDesayuno = new javax.swing.JComboBox<>();
        cmbFrutaDesayuno = new javax.swing.JComboBox<>();
        cmbBebidaDesayuno = new javax.swing.JComboBox<>();
        txtCaloriasCarbohidratoDesayuno = new javax.swing.JTextField();
        txtCaloriasGrasaDesayuno = new javax.swing.JTextField();
        txtCaloriasFrutaDesayuno = new javax.swing.JTextField();
        txtCaloriasBebidaDesayuno = new javax.swing.JTextField();
        txtCantidadCarbohidratoDesayuno = new javax.swing.JTextField();
        txtCantidadGrasaDesayuno = new javax.swing.JTextField();
        txtCantidadFrutaDesayuno = new javax.swing.JTextField();
        txtCantidadBebidaDesayuno = new javax.swing.JTextField();
        lblSubtotalDesayuno = new javax.swing.JLabel();
        txtSubtotalDesayuno = new javax.swing.JTextField();
        lblCantidadDesayuno = new javax.swing.JLabel();
        txtCantidadAlimentosDesayuno = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        pnlAlmuerzo = new javax.swing.JPanel();
        lblDesayuno1 = new javax.swing.JLabel();
        lblProteinaDesayuno1 = new javax.swing.JLabel();
        cmbProteinaAlmuerzo = new javax.swing.JComboBox<>();
        lblAlimento1 = new javax.swing.JLabel();
        lblCalorias1 = new javax.swing.JLabel();
        lblCantidad1 = new javax.swing.JLabel();
        txtCaloriasProteinaAlmuerzo = new javax.swing.JTextField();
        txtCantidadProteinaAlmuerzo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cmbCarbohidratoAlmuerzo = new javax.swing.JComboBox<>();
        cmbGrasaAlmuerzo = new javax.swing.JComboBox<>();
        cmbFrutaAlmuerzo = new javax.swing.JComboBox<>();
        cmbBebidaAlmuerzo = new javax.swing.JComboBox<>();
        txtCaloriasCarbohidratoAlmuerzo = new javax.swing.JTextField();
        txtCaloriasGrasaAlmuerzo = new javax.swing.JTextField();
        txtCaloriasFrutaAlmuerzo = new javax.swing.JTextField();
        txtCaloriasBebidaAlmuerzo = new javax.swing.JTextField();
        txtCantidadCarbohidratoAlmuerzo = new javax.swing.JTextField();
        txtCantidadGrasaAlmuerzo = new javax.swing.JTextField();
        txtCantidadFrutaAlmuerzo = new javax.swing.JTextField();
        txtCantidadBebidaAlmuerzo = new javax.swing.JTextField();
        lblSubtotalDesayuno1 = new javax.swing.JLabel();
        txtSubtotalAlmuerzo = new javax.swing.JTextField();
        lblCantidadDesayuno1 = new javax.swing.JLabel();
        txtCantidadAlimentosAlmuerzo = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        pnlCena = new javax.swing.JPanel();
        lblDesayuno2 = new javax.swing.JLabel();
        lblProteinaDesayuno2 = new javax.swing.JLabel();
        cmbProteinaCena = new javax.swing.JComboBox<>();
        lblAlimento2 = new javax.swing.JLabel();
        lblCalorias2 = new javax.swing.JLabel();
        lblCantidad2 = new javax.swing.JLabel();
        txtCaloriasProteinaCena = new javax.swing.JTextField();
        txtCantidadProteinaCena = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cmbCarbohidratoCena = new javax.swing.JComboBox<>();
        cmbGrasaCena = new javax.swing.JComboBox<>();
        cmbFrutaCena = new javax.swing.JComboBox<>();
        cmbBebidaCena = new javax.swing.JComboBox<>();
        txtCaloriasCarbohidratoCena = new javax.swing.JTextField();
        txtCaloriasGrasaCena = new javax.swing.JTextField();
        txtCaloriasFrutaCena = new javax.swing.JTextField();
        txtCaloriasBebidaCena = new javax.swing.JTextField();
        txtCantidadCarbohidratoCena = new javax.swing.JTextField();
        txtCantidadGrasaCena = new javax.swing.JTextField();
        txtCantidadFrutaCena = new javax.swing.JTextField();
        txtCantidadBebidaCena = new javax.swing.JTextField();
        lblSubtotalDesayuno2 = new javax.swing.JLabel();
        txtSubtotalCena = new javax.swing.JTextField();
        lblCantidadDesayuno2 = new javax.swing.JLabel();
        txtCantidadAlimentosCena = new javax.swing.JTextField();
        lblTotalCalorias = new javax.swing.JLabel();
        txtTotalCaloriasDia = new javax.swing.JTextField();
        txtMeta = new javax.swing.JTextField();
        lblDiferencia = new javax.swing.JLabel();
        txtDiferencia = new javax.swing.JTextField();
        lblPorcentaje = new javax.swing.JLabel();
        txtPorcentaje = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));

        lblTitulo.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 102, 255));
        lblTitulo.setText("JOVEN SALUDABLE");

        lblMetaCalorias.setText("Meta Calorias (kcal):");

        pnlDesayuno.setBackground(new java.awt.Color(255, 255, 153));
        pnlDesayuno.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.yellow, null));
        pnlDesayuno.setForeground(new java.awt.Color(255, 204, 51));

        lblDesayuno.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lblDesayuno.setText("DESAYUNO");

        lblProteinaDesayuno.setText("Proteina");

        cmbProteinaDesayuno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbProteinaDesayuno.addActionListener(this::cmbProteinaDesayunoActionPerformed);

        lblAlimento.setText("Alimento");

        lblCalorias.setText("Calorias");

        lblCantidad.setText("Cantidad");

        txtCaloriasProteinaDesayuno.setEditable(false);
        txtCaloriasProteinaDesayuno.setText("0");
        txtCaloriasProteinaDesayuno.addActionListener(this::txtCaloriasProteinaDesayunoActionPerformed);

        txtCantidadProteinaDesayuno.setText("0");

        jLabel1.setText("Carbohidrato");

        jLabel2.setText("Grasa");

        jLabel3.setText("Fruta");

        jLabel4.setText("Bebida");

        cmbCarbohidratoDesayuno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbCarbohidratoDesayuno.addActionListener(this::cmbCarbohidratoDesayunoActionPerformed);

        cmbGrasaDesayuno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbGrasaDesayuno.addActionListener(this::cmbGrasaDesayunoActionPerformed);

        cmbFrutaDesayuno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbFrutaDesayuno.addActionListener(this::cmbFrutaDesayunoActionPerformed);

        cmbBebidaDesayuno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbBebidaDesayuno.addActionListener(this::cmbBebidaDesayunoActionPerformed);

        txtCaloriasCarbohidratoDesayuno.setEditable(false);
        txtCaloriasCarbohidratoDesayuno.setText("0");
        txtCaloriasCarbohidratoDesayuno.addActionListener(this::txtCaloriasCarbohidratoDesayunoActionPerformed);

        txtCaloriasGrasaDesayuno.setEditable(false);
        txtCaloriasGrasaDesayuno.setText("0");
        txtCaloriasGrasaDesayuno.addActionListener(this::txtCaloriasGrasaDesayunoActionPerformed);

        txtCaloriasFrutaDesayuno.setEditable(false);
        txtCaloriasFrutaDesayuno.setText("0");
        txtCaloriasFrutaDesayuno.addActionListener(this::txtCaloriasFrutaDesayunoActionPerformed);

        txtCaloriasBebidaDesayuno.setEditable(false);
        txtCaloriasBebidaDesayuno.setText("0");
        txtCaloriasBebidaDesayuno.addActionListener(this::txtCaloriasBebidaDesayunoActionPerformed);

        txtCantidadCarbohidratoDesayuno.setText("0");

        txtCantidadGrasaDesayuno.setText("0");

        txtCantidadFrutaDesayuno.setText("0");

        txtCantidadBebidaDesayuno.setText("0");

        lblSubtotalDesayuno.setText("Subtotal Calorias: ");

        txtSubtotalDesayuno.setEditable(false);

        lblCantidadDesayuno.setText("Cantidad de alimentos: ");

        txtCantidadAlimentosDesayuno.setEditable(false);

        javax.swing.GroupLayout pnlDesayunoLayout = new javax.swing.GroupLayout(pnlDesayuno);
        pnlDesayuno.setLayout(pnlDesayunoLayout);
        pnlDesayunoLayout.setHorizontalGroup(
            pnlDesayunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDesayunoLayout.createSequentialGroup()
                .addGroup(pnlDesayunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlDesayunoLayout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(lblDesayuno))
                    .addGroup(pnlDesayunoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(pnlDesayunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblProteinaDesayuno)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlDesayunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbBebidaDesayuno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbFrutaDesayuno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbGrasaDesayuno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbCarbohidratoDesayuno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAlimento)
                            .addComponent(cmbProteinaDesayuno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(pnlDesayunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtCaloriasFrutaDesayuno, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlDesayunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblCalorias)
                        .addComponent(txtCaloriasProteinaDesayuno, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtCaloriasCarbohidratoDesayuno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(txtCaloriasGrasaDesayuno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(txtCaloriasBebidaDesayuno, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addGroup(pnlDesayunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDesayunoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlDesayunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCantidad, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCantidadProteinaDesayuno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCantidadCarbohidratoDesayuno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22))
                    .addGroup(pnlDesayunoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnlDesayunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCantidadGrasaDesayuno, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCantidadFrutaDesayuno, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCantidadBebidaDesayuno, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(pnlDesayunoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDesayunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDesayunoLayout.createSequentialGroup()
                        .addComponent(lblSubtotalDesayuno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtSubtotalDesayuno, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDesayunoLayout.createSequentialGroup()
                        .addComponent(lblCantidadDesayuno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCantidadAlimentosDesayuno)))
                .addGap(74, 74, 74))
        );
        pnlDesayunoLayout.setVerticalGroup(
            pnlDesayunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDesayunoLayout.createSequentialGroup()
                .addComponent(lblDesayuno)
                .addGap(2, 2, 2)
                .addGroup(pnlDesayunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAlimento)
                    .addComponent(lblCalorias)
                    .addComponent(lblCantidad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDesayunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProteinaDesayuno)
                    .addComponent(cmbProteinaDesayuno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCaloriasProteinaDesayuno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidadProteinaDesayuno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDesayunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbCarbohidratoDesayuno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCaloriasCarbohidratoDesayuno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidadCarbohidratoDesayuno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(pnlDesayunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbGrasaDesayuno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCaloriasGrasaDesayuno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidadGrasaDesayuno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(pnlDesayunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbFrutaDesayuno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCaloriasFrutaDesayuno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidadFrutaDesayuno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDesayunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbBebidaDesayuno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCaloriasBebidaDesayuno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidadBebidaDesayuno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlDesayunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSubtotalDesayuno, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtSubtotalDesayuno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDesayunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCantidadDesayuno)
                    .addComponent(txtCantidadAlimentosDesayuno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pnlAlmuerzo.setBackground(new java.awt.Color(255, 204, 153));
        pnlAlmuerzo.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.green, null));
        pnlAlmuerzo.setForeground(new java.awt.Color(255, 204, 51));

        lblDesayuno1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lblDesayuno1.setText("ALMUERZO");

        lblProteinaDesayuno1.setText("Proteina");

        cmbProteinaAlmuerzo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbProteinaAlmuerzo.addActionListener(this::cmbProteinaAlmuerzoActionPerformed);

        lblAlimento1.setText("Alimento");

        lblCalorias1.setText("Calorias");

        lblCantidad1.setText("Cantidad");

        txtCaloriasProteinaAlmuerzo.setEditable(false);
        txtCaloriasProteinaAlmuerzo.setText("0");
        txtCaloriasProteinaAlmuerzo.addActionListener(this::txtCaloriasProteinaAlmuerzoActionPerformed);

        txtCantidadProteinaAlmuerzo.setText("0");

        jLabel5.setText("Carbohidrato");

        jLabel6.setText("Grasa");

        jLabel7.setText("Fruta");

        jLabel8.setText("Bebida");

        cmbCarbohidratoAlmuerzo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbCarbohidratoAlmuerzo.addActionListener(this::cmbCarbohidratoAlmuerzoActionPerformed);

        cmbGrasaAlmuerzo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbGrasaAlmuerzo.addActionListener(this::cmbGrasaAlmuerzoActionPerformed);

        cmbFrutaAlmuerzo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbFrutaAlmuerzo.addActionListener(this::cmbFrutaAlmuerzoActionPerformed);

        cmbBebidaAlmuerzo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbBebidaAlmuerzo.addActionListener(this::cmbBebidaAlmuerzoActionPerformed);

        txtCaloriasCarbohidratoAlmuerzo.setEditable(false);
        txtCaloriasCarbohidratoAlmuerzo.setText("0");
        txtCaloriasCarbohidratoAlmuerzo.addActionListener(this::txtCaloriasCarbohidratoAlmuerzoActionPerformed);

        txtCaloriasGrasaAlmuerzo.setEditable(false);
        txtCaloriasGrasaAlmuerzo.setText("0");
        txtCaloriasGrasaAlmuerzo.addActionListener(this::txtCaloriasGrasaAlmuerzoActionPerformed);

        txtCaloriasFrutaAlmuerzo.setEditable(false);
        txtCaloriasFrutaAlmuerzo.setText("0");
        txtCaloriasFrutaAlmuerzo.addActionListener(this::txtCaloriasFrutaAlmuerzoActionPerformed);

        txtCaloriasBebidaAlmuerzo.setEditable(false);
        txtCaloriasBebidaAlmuerzo.setText("0");
        txtCaloriasBebidaAlmuerzo.addActionListener(this::txtCaloriasBebidaAlmuerzoActionPerformed);

        txtCantidadCarbohidratoAlmuerzo.setText("0");

        txtCantidadGrasaAlmuerzo.setText("0");

        txtCantidadFrutaAlmuerzo.setText("0");

        txtCantidadBebidaAlmuerzo.setText("0");

        lblSubtotalDesayuno1.setText("Subtotal Calorias: ");

        txtSubtotalAlmuerzo.setEditable(false);

        lblCantidadDesayuno1.setText("Cantidad de alimentos: ");

        txtCantidadAlimentosAlmuerzo.setEditable(false);

        javax.swing.GroupLayout pnlAlmuerzoLayout = new javax.swing.GroupLayout(pnlAlmuerzo);
        pnlAlmuerzo.setLayout(pnlAlmuerzoLayout);
        pnlAlmuerzoLayout.setHorizontalGroup(
            pnlAlmuerzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAlmuerzoLayout.createSequentialGroup()
                .addGroup(pnlAlmuerzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlAlmuerzoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlAlmuerzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlAlmuerzoLayout.createSequentialGroup()
                                .addComponent(lblCantidadDesayuno1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCantidadAlimentosAlmuerzo))
                            .addGroup(pnlAlmuerzoLayout.createSequentialGroup()
                                .addComponent(lblSubtotalDesayuno1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtSubtotalAlmuerzo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlAlmuerzoLayout.createSequentialGroup()
                        .addGroup(pnlAlmuerzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlAlmuerzoLayout.createSequentialGroup()
                                .addGap(128, 128, 128)
                                .addComponent(lblDesayuno1))
                            .addGroup(pnlAlmuerzoLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(pnlAlmuerzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblProteinaDesayuno1)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pnlAlmuerzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbBebidaAlmuerzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbFrutaAlmuerzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbGrasaAlmuerzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbCarbohidratoAlmuerzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblAlimento1)
                                    .addComponent(cmbProteinaAlmuerzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(pnlAlmuerzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtCaloriasFrutaAlmuerzo, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlAlmuerzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblCalorias1)
                                .addComponent(txtCaloriasProteinaAlmuerzo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtCaloriasCarbohidratoAlmuerzo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(txtCaloriasGrasaAlmuerzo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(txtCaloriasBebidaAlmuerzo, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))))
                .addGroup(pnlAlmuerzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAlmuerzoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlAlmuerzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCantidad1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCantidadProteinaAlmuerzo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCantidadCarbohidratoAlmuerzo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22))
                    .addGroup(pnlAlmuerzoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnlAlmuerzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCantidadGrasaAlmuerzo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCantidadFrutaAlmuerzo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCantidadBebidaAlmuerzo, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnlAlmuerzoLayout.setVerticalGroup(
            pnlAlmuerzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAlmuerzoLayout.createSequentialGroup()
                .addComponent(lblDesayuno1)
                .addGap(2, 2, 2)
                .addGroup(pnlAlmuerzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAlimento1)
                    .addComponent(lblCalorias1)
                    .addComponent(lblCantidad1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAlmuerzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProteinaDesayuno1)
                    .addComponent(cmbProteinaAlmuerzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCaloriasProteinaAlmuerzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidadProteinaAlmuerzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAlmuerzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbCarbohidratoAlmuerzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCaloriasCarbohidratoAlmuerzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidadCarbohidratoAlmuerzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(pnlAlmuerzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbGrasaAlmuerzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCaloriasGrasaAlmuerzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidadGrasaAlmuerzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(pnlAlmuerzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbFrutaAlmuerzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCaloriasFrutaAlmuerzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidadFrutaAlmuerzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAlmuerzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cmbBebidaAlmuerzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCaloriasBebidaAlmuerzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidadBebidaAlmuerzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(pnlAlmuerzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSubtotalDesayuno1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtSubtotalAlmuerzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAlmuerzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCantidadDesayuno1)
                    .addComponent(txtCantidadAlimentosAlmuerzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 371, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlAlmuerzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlAlmuerzo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlCena.setBackground(new java.awt.Color(204, 204, 255));
        pnlCena.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.magenta, null));
        pnlCena.setForeground(new java.awt.Color(255, 204, 51));

        lblDesayuno2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lblDesayuno2.setText("CENA");

        lblProteinaDesayuno2.setText("Proteina");

        cmbProteinaCena.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbProteinaCena.addActionListener(this::cmbProteinaCenaActionPerformed);

        lblAlimento2.setText("Alimento");

        lblCalorias2.setText("Calorias");

        lblCantidad2.setText("Cantidad");

        txtCaloriasProteinaCena.setEditable(false);
        txtCaloriasProteinaCena.setText("0");
        txtCaloriasProteinaCena.addActionListener(this::txtCaloriasProteinaCenaActionPerformed);

        txtCantidadProteinaCena.setText("0");

        jLabel9.setText("Carbohidrato");

        jLabel10.setText("Grasa");

        jLabel11.setText("Fruta");

        jLabel12.setText("Bebida");

        cmbCarbohidratoCena.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbCarbohidratoCena.addActionListener(this::cmbCarbohidratoCenaActionPerformed);

        cmbGrasaCena.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbGrasaCena.addActionListener(this::cmbGrasaCenaActionPerformed);

        cmbFrutaCena.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbFrutaCena.addActionListener(this::cmbFrutaCenaActionPerformed);

        cmbBebidaCena.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbBebidaCena.addActionListener(this::cmbBebidaCenaActionPerformed);

        txtCaloriasCarbohidratoCena.setEditable(false);
        txtCaloriasCarbohidratoCena.setText("0");
        txtCaloriasCarbohidratoCena.addActionListener(this::txtCaloriasCarbohidratoCenaActionPerformed);

        txtCaloriasGrasaCena.setEditable(false);
        txtCaloriasGrasaCena.setText("0");
        txtCaloriasGrasaCena.addActionListener(this::txtCaloriasGrasaCenaActionPerformed);

        txtCaloriasFrutaCena.setEditable(false);
        txtCaloriasFrutaCena.setText("0");
        txtCaloriasFrutaCena.addActionListener(this::txtCaloriasFrutaCenaActionPerformed);

        txtCaloriasBebidaCena.setEditable(false);
        txtCaloriasBebidaCena.setText("0");
        txtCaloriasBebidaCena.addActionListener(this::txtCaloriasBebidaCenaActionPerformed);

        txtCantidadCarbohidratoCena.setText("0");

        txtCantidadGrasaCena.setText("0");

        txtCantidadFrutaCena.setText("0");

        txtCantidadBebidaCena.setText("0");

        lblSubtotalDesayuno2.setText("Subtotal Calorias: ");

        txtSubtotalCena.setEditable(false);

        lblCantidadDesayuno2.setText("Cantidad de alimentos: ");

        txtCantidadAlimentosCena.setEditable(false);

        javax.swing.GroupLayout pnlCenaLayout = new javax.swing.GroupLayout(pnlCena);
        pnlCena.setLayout(pnlCenaLayout);
        pnlCenaLayout.setHorizontalGroup(
            pnlCenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCenaLayout.createSequentialGroup()
                .addGroup(pnlCenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlCenaLayout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(lblDesayuno2))
                    .addGroup(pnlCenaLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(pnlCenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblProteinaDesayuno2)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlCenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbBebidaCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbFrutaCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbGrasaCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbCarbohidratoCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAlimento2)
                            .addComponent(cmbProteinaCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(pnlCenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtCaloriasFrutaCena, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlCenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblCalorias2)
                        .addComponent(txtCaloriasProteinaCena, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtCaloriasCarbohidratoCena, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(txtCaloriasGrasaCena, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(txtCaloriasBebidaCena, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addGroup(pnlCenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCenaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addGroup(pnlCenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCantidad2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCantidadProteinaCena, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCantidadCarbohidratoCena, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22))
                    .addGroup(pnlCenaLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnlCenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCantidadGrasaCena, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCantidadFrutaCena, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCantidadBebidaCena, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(pnlCenaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCenaLayout.createSequentialGroup()
                        .addComponent(lblCantidadDesayuno2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCantidadAlimentosCena, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))
                    .addGroup(pnlCenaLayout.createSequentialGroup()
                        .addComponent(lblSubtotalDesayuno2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtSubtotalCena, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlCenaLayout.setVerticalGroup(
            pnlCenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCenaLayout.createSequentialGroup()
                .addComponent(lblDesayuno2)
                .addGap(2, 2, 2)
                .addGroup(pnlCenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAlimento2)
                    .addComponent(lblCalorias2)
                    .addComponent(lblCantidad2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProteinaDesayuno2)
                    .addComponent(cmbProteinaCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCaloriasProteinaCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidadProteinaCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cmbCarbohidratoCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCaloriasCarbohidratoCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidadCarbohidratoCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(pnlCenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cmbGrasaCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCaloriasGrasaCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidadGrasaCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(pnlCenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cmbFrutaCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCaloriasFrutaCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidadFrutaCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cmbBebidaCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCaloriasBebidaCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidadBebidaCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(pnlCenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSubtotalDesayuno2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtSubtotalCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCantidadDesayuno2)
                    .addComponent(txtCantidadAlimentosCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 363, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 294, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlCena, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblTotalCalorias.setFont(new java.awt.Font("Segoe UI Historic", 3, 14)); // NOI18N
        lblTotalCalorias.setForeground(new java.awt.Color(102, 0, 255));
        lblTotalCalorias.setText("TOTAL CALORIAS DEL DIA:");

        txtTotalCaloriasDia.setEditable(false);
        txtTotalCaloriasDia.setText("0");

        txtMeta.addActionListener(this::txtMetaActionPerformed);

        lblDiferencia.setFont(new java.awt.Font("Javanese Text", 2, 12)); // NOI18N
        lblDiferencia.setForeground(new java.awt.Color(204, 0, 0));
        lblDiferencia.setText("DIFERENCIA:");

        txtDiferencia.setEditable(false);
        txtDiferencia.setText("0");

        lblPorcentaje.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPorcentaje.setForeground(new java.awt.Color(51, 102, 0));
        lblPorcentaje.setText("PORCENTAJE ALCANZADO:");

        txtPorcentaje.setEditable(false);

        btnCalcular.setText("CALCULAR");
        btnCalcular.addActionListener(this::btnCalcularActionPerformed);

        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        btnSalir.setText("SALIR");
        btnSalir.addActionListener(this::btnSalirActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pnlDesayuno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblMetaCalorias)
                                .addGap(18, 18, 18)
                                .addComponent(txtMeta, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(294, 294, 294)
                                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblTotalCalorias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTotalCaloriasDia))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDiferencia)
                            .addComponent(txtDiferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPorcentaje))))
                .addContainerGap(142, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addComponent(btnCalcular)
                .addGap(256, 256, 256)
                .addComponent(btnLimpiar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addGap(221, 221, 221))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMetaCalorias)
                            .addComponent(txtMeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlDesayuno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalCalorias)
                    .addComponent(lblDiferencia)
                    .addComponent(lblPorcentaje))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTotalCaloriasDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtDiferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcular)
                    .addComponent(btnLimpiar)
                    .addComponent(btnSalir))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMetaActionPerformed

    private void txtCaloriasProteinaDesayunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCaloriasProteinaDesayunoActionPerformed
        // TODO add your handling code here:
        setEditable(false);
    }//GEN-LAST:event_txtCaloriasProteinaDesayunoActionPerformed

    private void txtCaloriasCarbohidratoDesayunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCaloriasCarbohidratoDesayunoActionPerformed
        // TODO add your handling code here:
        setEditable(false);
    }//GEN-LAST:event_txtCaloriasCarbohidratoDesayunoActionPerformed

    private void txtCaloriasGrasaDesayunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCaloriasGrasaDesayunoActionPerformed
        // TODO add your handling code here:
        setEditable(false);
    }//GEN-LAST:event_txtCaloriasGrasaDesayunoActionPerformed

    private void txtCaloriasFrutaDesayunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCaloriasFrutaDesayunoActionPerformed
        // TODO add your handling code here:
        setEditable(false);
    }//GEN-LAST:event_txtCaloriasFrutaDesayunoActionPerformed

    private void txtCaloriasBebidaDesayunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCaloriasBebidaDesayunoActionPerformed
        // TODO add your handling code here:
        setEditable(false);
    }//GEN-LAST:event_txtCaloriasBebidaDesayunoActionPerformed

    private void txtCaloriasProteinaAlmuerzoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCaloriasProteinaAlmuerzoActionPerformed
        // TODO add your handling code here:
        setEditable(false);
    }//GEN-LAST:event_txtCaloriasProteinaAlmuerzoActionPerformed

    private void txtCaloriasCarbohidratoAlmuerzoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCaloriasCarbohidratoAlmuerzoActionPerformed
        // TODO add your handling code here:
        setEditable(false);
    }//GEN-LAST:event_txtCaloriasCarbohidratoAlmuerzoActionPerformed

    private void txtCaloriasGrasaAlmuerzoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCaloriasGrasaAlmuerzoActionPerformed
        // TODO add your handling code here:
        setEditable(false);
    }//GEN-LAST:event_txtCaloriasGrasaAlmuerzoActionPerformed

    private void txtCaloriasFrutaAlmuerzoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCaloriasFrutaAlmuerzoActionPerformed
        // TODO add your handling code here:
        setEditable(false);
    }//GEN-LAST:event_txtCaloriasFrutaAlmuerzoActionPerformed

    private void txtCaloriasBebidaAlmuerzoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCaloriasBebidaAlmuerzoActionPerformed
        // TODO add your handling code here:
        setEditable(false);
    }//GEN-LAST:event_txtCaloriasBebidaAlmuerzoActionPerformed

    private void txtCaloriasProteinaCenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCaloriasProteinaCenaActionPerformed
        // TODO add your handling code here:
        setEditable(false);
    }//GEN-LAST:event_txtCaloriasProteinaCenaActionPerformed

    private void txtCaloriasCarbohidratoCenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCaloriasCarbohidratoCenaActionPerformed
        // TODO add your handling code here:
        setEditable(false);
    }//GEN-LAST:event_txtCaloriasCarbohidratoCenaActionPerformed

    private void txtCaloriasGrasaCenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCaloriasGrasaCenaActionPerformed
        // TODO add your handling code here:
        setEditable(false);
    }//GEN-LAST:event_txtCaloriasGrasaCenaActionPerformed

    private void txtCaloriasFrutaCenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCaloriasFrutaCenaActionPerformed
        // TODO add your handling code here:
        setEditable(false);
    }//GEN-LAST:event_txtCaloriasFrutaCenaActionPerformed

    private void txtCaloriasBebidaCenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCaloriasBebidaCenaActionPerformed
        // TODO add your handling code here:
        setEditable(false);
    }//GEN-LAST:event_txtCaloriasBebidaCenaActionPerformed

    private void cmbProteinaDesayunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProteinaDesayunoActionPerformed
        // TODO add your handling code here:
        actualizarCalorias(cmbProteinaDesayuno, txtCaloriasProteinaDesayuno);
    }//GEN-LAST:event_cmbProteinaDesayunoActionPerformed

    private void cmbCarbohidratoDesayunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCarbohidratoDesayunoActionPerformed
        // TODO add your handling code here:
        actualizarCalorias(cmbCarbohidratoDesayuno, txtCaloriasCarbohidratoDesayuno);
    }//GEN-LAST:event_cmbCarbohidratoDesayunoActionPerformed

    private void cmbGrasaDesayunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbGrasaDesayunoActionPerformed
        // TODO add your handling code here:
        actualizarCalorias(cmbGrasaDesayuno, txtCaloriasGrasaDesayuno);
    }//GEN-LAST:event_cmbGrasaDesayunoActionPerformed

    private void cmbFrutaDesayunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFrutaDesayunoActionPerformed
        // TODO add your handling code here:
        actualizarCalorias(cmbFrutaDesayuno, txtCaloriasFrutaDesayuno);
    }//GEN-LAST:event_cmbFrutaDesayunoActionPerformed

    private void cmbBebidaDesayunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBebidaDesayunoActionPerformed
        // TODO add your handling code here:
        actualizarCalorias(cmbBebidaDesayuno, txtCaloriasBebidaDesayuno);
    }//GEN-LAST:event_cmbBebidaDesayunoActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
        javax.swing.JOptionPane.showMessageDialog(this, "Calcular");
        int subtotalDesayuno = 0;
int cantidadDesayuno = 0;

subtotalDesayuno += buscarCalorias(cmbProteinaDesayuno.getSelectedItem().toString())
        * obtenerCantidad(txtCantidadProteinaDesayuno.getText());
cantidadDesayuno += obtenerCantidad(txtCantidadProteinaDesayuno.getText());

subtotalDesayuno += buscarCalorias(cmbCarbohidratoDesayuno.getSelectedItem().toString())
        * obtenerCantidad(txtCantidadCarbohidratoDesayuno.getText());
cantidadDesayuno += obtenerCantidad(txtCantidadCarbohidratoDesayuno.getText());

subtotalDesayuno += buscarCalorias(cmbGrasaDesayuno.getSelectedItem().toString())
        * obtenerCantidad(txtCantidadGrasaDesayuno.getText());
cantidadDesayuno += obtenerCantidad(txtCantidadGrasaDesayuno.getText());

subtotalDesayuno += buscarCalorias(cmbFrutaDesayuno.getSelectedItem().toString())
        * obtenerCantidad(txtCantidadFrutaDesayuno.getText());
cantidadDesayuno += obtenerCantidad(txtCantidadFrutaDesayuno.getText());

subtotalDesayuno += buscarCalorias(cmbBebidaDesayuno.getSelectedItem().toString())
        * obtenerCantidad(txtCantidadBebidaDesayuno.getText());
cantidadDesayuno += obtenerCantidad(txtCantidadBebidaDesayuno.getText());

txtSubtotalDesayuno.setText(String.valueOf(subtotalDesayuno));
txtCantidadAlimentosDesayuno.setText(String.valueOf(cantidadDesayuno));
int subtotalAlmuerzo = 0;
int cantidadAlmuerzo = 0;

subtotalAlmuerzo += buscarCalorias(cmbProteinaAlmuerzo.getSelectedItem().toString())
        * obtenerCantidad(txtCantidadProteinaAlmuerzo.getText());
cantidadAlmuerzo += obtenerCantidad(txtCantidadProteinaAlmuerzo.getText());

subtotalAlmuerzo += buscarCalorias(cmbCarbohidratoAlmuerzo.getSelectedItem().toString())
        * obtenerCantidad(txtCantidadCarbohidratoAlmuerzo.getText());
cantidadAlmuerzo += obtenerCantidad(txtCantidadCarbohidratoAlmuerzo.getText());

subtotalAlmuerzo += buscarCalorias(cmbGrasaAlmuerzo.getSelectedItem().toString())
        * obtenerCantidad(txtCantidadGrasaAlmuerzo.getText());
cantidadAlmuerzo += obtenerCantidad(txtCantidadGrasaAlmuerzo.getText());

subtotalAlmuerzo += buscarCalorias(cmbFrutaAlmuerzo.getSelectedItem().toString())
        * obtenerCantidad(txtCantidadFrutaAlmuerzo.getText());
cantidadAlmuerzo += obtenerCantidad(txtCantidadFrutaAlmuerzo.getText());

subtotalAlmuerzo += buscarCalorias(cmbBebidaAlmuerzo.getSelectedItem().toString())
        * obtenerCantidad(txtCantidadBebidaAlmuerzo.getText());
cantidadAlmuerzo += obtenerCantidad(txtCantidadBebidaAlmuerzo.getText());

txtSubtotalAlmuerzo.setText(String.valueOf(subtotalAlmuerzo));
txtCantidadAlimentosAlmuerzo.setText(String.valueOf(cantidadAlmuerzo));
//================ CENA ================

int subtotalCena = 0;
int cantidadCena = 0;

subtotalCena += buscarCalorias(cmbProteinaCena.getSelectedItem().toString())
        * obtenerCantidad(txtCantidadProteinaCena.getText());
cantidadCena += obtenerCantidad(txtCantidadProteinaCena.getText());

subtotalCena += buscarCalorias(cmbCarbohidratoCena.getSelectedItem().toString())
        * obtenerCantidad(txtCantidadCarbohidratoCena.getText());
cantidadCena += obtenerCantidad(txtCantidadCarbohidratoCena.getText());

subtotalCena += buscarCalorias(cmbGrasaCena.getSelectedItem().toString())
        * obtenerCantidad(txtCantidadGrasaCena.getText());
cantidadCena += obtenerCantidad(txtCantidadGrasaCena.getText());

subtotalCena += buscarCalorias(cmbFrutaCena.getSelectedItem().toString())
        * obtenerCantidad(txtCantidadFrutaCena.getText());
cantidadCena += obtenerCantidad(txtCantidadFrutaCena.getText());

subtotalCena += buscarCalorias(cmbBebidaCena.getSelectedItem().toString())
        * obtenerCantidad(txtCantidadBebidaCena.getText());
cantidadCena += obtenerCantidad(txtCantidadBebidaCena.getText());

txtSubtotalCena.setText(String.valueOf(subtotalCena));
txtCantidadAlimentosCena.setText(String.valueOf(cantidadCena));
int totalDia = subtotalDesayuno + subtotalAlmuerzo + subtotalCena;

txtTotalCaloriasDia.setText(String.valueOf(totalDia));
int meta;

try{
    meta = Integer.parseInt(txtMeta.getText());
}catch(NumberFormatException e){
    meta = 2000;
}
int diferencia = totalDia - meta;

txtDiferencia.setText(String.valueOf(diferencia));
double porcentaje = 0;

if(meta > 0){
    porcentaje = (totalDia * 100.0) / meta;
}

txtPorcentaje.setText(String.format("%.2f %%", porcentaje));
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void cmbProteinaAlmuerzoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProteinaAlmuerzoActionPerformed
        // TODO add your handling code here:
        actualizarCalorias(cmbProteinaAlmuerzo, txtCaloriasProteinaAlmuerzo);
    }//GEN-LAST:event_cmbProteinaAlmuerzoActionPerformed

    private void cmbCarbohidratoAlmuerzoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCarbohidratoAlmuerzoActionPerformed
        // TODO add your handling code here:
        actualizarCalorias(cmbCarbohidratoAlmuerzo, txtCaloriasCarbohidratoAlmuerzo);
    }//GEN-LAST:event_cmbCarbohidratoAlmuerzoActionPerformed

    private void cmbGrasaAlmuerzoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbGrasaAlmuerzoActionPerformed
        // TODO add your handling code here:
        actualizarCalorias(cmbGrasaAlmuerzo, txtCaloriasGrasaAlmuerzo);
    }//GEN-LAST:event_cmbGrasaAlmuerzoActionPerformed

    private void cmbFrutaAlmuerzoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFrutaAlmuerzoActionPerformed
        // TODO add your handling code here:
        actualizarCalorias(cmbFrutaAlmuerzo, txtCaloriasFrutaAlmuerzo);
    }//GEN-LAST:event_cmbFrutaAlmuerzoActionPerformed

    private void cmbBebidaAlmuerzoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBebidaAlmuerzoActionPerformed
        // TODO add your handling code here:
        actualizarCalorias(cmbBebidaAlmuerzo, txtCaloriasBebidaAlmuerzo);
    }//GEN-LAST:event_cmbBebidaAlmuerzoActionPerformed

    private void cmbProteinaCenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProteinaCenaActionPerformed
        // TODO add your handling code here:
        actualizarCalorias(cmbProteinaCena, txtCaloriasProteinaCena);
    }//GEN-LAST:event_cmbProteinaCenaActionPerformed

    private void cmbCarbohidratoCenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCarbohidratoCenaActionPerformed
        // TODO add your handling code here:
        actualizarCalorias(cmbCarbohidratoCena, txtCaloriasCarbohidratoCena);
    }//GEN-LAST:event_cmbCarbohidratoCenaActionPerformed

    private void cmbGrasaCenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbGrasaCenaActionPerformed
        // TODO add your handling code here:
        actualizarCalorias(cmbGrasaCena, txtCaloriasGrasaCena);
    }//GEN-LAST:event_cmbGrasaCenaActionPerformed

    private void cmbFrutaCenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFrutaCenaActionPerformed
        // TODO add your handling code here:
        actualizarCalorias(cmbFrutaCena, txtCaloriasFrutaCena);
    }//GEN-LAST:event_cmbFrutaCenaActionPerformed

    private void cmbBebidaCenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBebidaCenaActionPerformed
        // TODO add your handling code here:
        actualizarCalorias(cmbBebidaCena, txtCaloriasBebidaCena);
    }//GEN-LAST:event_cmbBebidaCenaActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        //================ LIMPIAR DESAYUNO ================

cmbProteinaDesayuno.setSelectedIndex(0);
cmbCarbohidratoDesayuno.setSelectedIndex(0);
cmbGrasaDesayuno.setSelectedIndex(0);
cmbFrutaDesayuno.setSelectedIndex(0);
cmbBebidaDesayuno.setSelectedIndex(0);

txtCantidadProteinaDesayuno.setText("1");
txtCantidadCarbohidratoDesayuno.setText("1");
txtCantidadGrasaDesayuno.setText("1");
txtCantidadFrutaDesayuno.setText("1");
txtCantidadBebidaDesayuno.setText("1");

txtSubtotalDesayuno.setText("0");
txtCantidadAlimentosDesayuno.setText("0");


//================ LIMPIAR ALMUERZO ================

cmbProteinaAlmuerzo.setSelectedIndex(0);
cmbCarbohidratoAlmuerzo.setSelectedIndex(0);
cmbGrasaAlmuerzo.setSelectedIndex(0);
cmbFrutaAlmuerzo.setSelectedIndex(0);
cmbBebidaAlmuerzo.setSelectedIndex(0);

txtCantidadProteinaAlmuerzo.setText("1");
txtCantidadCarbohidratoAlmuerzo.setText("1");
txtCantidadGrasaAlmuerzo.setText("1");
txtCantidadFrutaAlmuerzo.setText("1");
txtCantidadBebidaAlmuerzo.setText("1");

txtSubtotalAlmuerzo.setText("0");
txtCantidadAlimentosAlmuerzo.setText("0");


//================ LIMPIAR CENA ================

cmbProteinaCena.setSelectedIndex(0);
cmbCarbohidratoCena.setSelectedIndex(0);
cmbGrasaCena.setSelectedIndex(0);
cmbFrutaCena.setSelectedIndex(0);
cmbBebidaCena.setSelectedIndex(0);

txtCantidadProteinaCena.setText("1");
txtCantidadCarbohidratoCena.setText("1");
txtCantidadGrasaCena.setText("1");
txtCantidadFrutaCena.setText("1");
txtCantidadBebidaCena.setText("1");

txtSubtotalCena.setText("0");
txtCantidadAlimentosCena.setText("0");


//================ RESULTADOS ================

txtTotalCaloriasDia.setText("0");
txtDiferencia.setText("0");
txtPorcentaje.setText("0 %");

// Meta (la de abajo)
txtMeta.setText("2000");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        int opcion = javax.swing.JOptionPane.showConfirmDialog(
        this,
        "¿Desea salir del programa?",
        "Confirmar",
        javax.swing.JOptionPane.YES_NO_OPTION);

if (opcion == javax.swing.JOptionPane.YES_OPTION) {
    System.exit(0);
}
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new jfrmJovenSaludable().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cmbBebidaAlmuerzo;
    private javax.swing.JComboBox<String> cmbBebidaCena;
    private javax.swing.JComboBox<String> cmbBebidaDesayuno;
    private javax.swing.JComboBox<String> cmbCarbohidratoAlmuerzo;
    private javax.swing.JComboBox<String> cmbCarbohidratoCena;
    private javax.swing.JComboBox<String> cmbCarbohidratoDesayuno;
    private javax.swing.JComboBox<String> cmbFrutaAlmuerzo;
    private javax.swing.JComboBox<String> cmbFrutaCena;
    private javax.swing.JComboBox<String> cmbFrutaDesayuno;
    private javax.swing.JComboBox<String> cmbGrasaAlmuerzo;
    private javax.swing.JComboBox<String> cmbGrasaCena;
    private javax.swing.JComboBox<String> cmbGrasaDesayuno;
    private javax.swing.JComboBox<String> cmbProteinaAlmuerzo;
    private javax.swing.JComboBox<String> cmbProteinaCena;
    private javax.swing.JComboBox<String> cmbProteinaDesayuno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAlimento;
    private javax.swing.JLabel lblAlimento1;
    private javax.swing.JLabel lblAlimento2;
    private javax.swing.JLabel lblCalorias;
    private javax.swing.JLabel lblCalorias1;
    private javax.swing.JLabel lblCalorias2;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblCantidad1;
    private javax.swing.JLabel lblCantidad2;
    private javax.swing.JLabel lblCantidadDesayuno;
    private javax.swing.JLabel lblCantidadDesayuno1;
    private javax.swing.JLabel lblCantidadDesayuno2;
    private javax.swing.JLabel lblDesayuno;
    private javax.swing.JLabel lblDesayuno1;
    private javax.swing.JLabel lblDesayuno2;
    private javax.swing.JLabel lblDiferencia;
    private javax.swing.JLabel lblMetaCalorias;
    private javax.swing.JLabel lblPorcentaje;
    private javax.swing.JLabel lblProteinaDesayuno;
    private javax.swing.JLabel lblProteinaDesayuno1;
    private javax.swing.JLabel lblProteinaDesayuno2;
    private javax.swing.JLabel lblSubtotalDesayuno;
    private javax.swing.JLabel lblSubtotalDesayuno1;
    private javax.swing.JLabel lblSubtotalDesayuno2;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTotalCalorias;
    private javax.swing.JPanel pnlAlmuerzo;
    private javax.swing.JPanel pnlCena;
    private javax.swing.JPanel pnlDesayuno;
    private javax.swing.JTextField txtCaloriasBebidaAlmuerzo;
    private javax.swing.JTextField txtCaloriasBebidaCena;
    private javax.swing.JTextField txtCaloriasBebidaDesayuno;
    private javax.swing.JTextField txtCaloriasCarbohidratoAlmuerzo;
    private javax.swing.JTextField txtCaloriasCarbohidratoCena;
    private javax.swing.JTextField txtCaloriasCarbohidratoDesayuno;
    private javax.swing.JTextField txtCaloriasFrutaAlmuerzo;
    private javax.swing.JTextField txtCaloriasFrutaCena;
    private javax.swing.JTextField txtCaloriasFrutaDesayuno;
    private javax.swing.JTextField txtCaloriasGrasaAlmuerzo;
    private javax.swing.JTextField txtCaloriasGrasaCena;
    private javax.swing.JTextField txtCaloriasGrasaDesayuno;
    private javax.swing.JTextField txtCaloriasProteinaAlmuerzo;
    private javax.swing.JTextField txtCaloriasProteinaCena;
    private javax.swing.JTextField txtCaloriasProteinaDesayuno;
    private javax.swing.JTextField txtCantidadAlimentosAlmuerzo;
    private javax.swing.JTextField txtCantidadAlimentosCena;
    private javax.swing.JTextField txtCantidadAlimentosDesayuno;
    private javax.swing.JTextField txtCantidadBebidaAlmuerzo;
    private javax.swing.JTextField txtCantidadBebidaCena;
    private javax.swing.JTextField txtCantidadBebidaDesayuno;
    private javax.swing.JTextField txtCantidadCarbohidratoAlmuerzo;
    private javax.swing.JTextField txtCantidadCarbohidratoCena;
    private javax.swing.JTextField txtCantidadCarbohidratoDesayuno;
    private javax.swing.JTextField txtCantidadFrutaAlmuerzo;
    private javax.swing.JTextField txtCantidadFrutaCena;
    private javax.swing.JTextField txtCantidadFrutaDesayuno;
    private javax.swing.JTextField txtCantidadGrasaAlmuerzo;
    private javax.swing.JTextField txtCantidadGrasaCena;
    private javax.swing.JTextField txtCantidadGrasaDesayuno;
    private javax.swing.JTextField txtCantidadProteinaAlmuerzo;
    private javax.swing.JTextField txtCantidadProteinaCena;
    private javax.swing.JTextField txtCantidadProteinaDesayuno;
    private javax.swing.JTextField txtDiferencia;
    private javax.swing.JTextField txtMeta;
    private javax.swing.JTextField txtPorcentaje;
    private javax.swing.JTextField txtSubtotalAlmuerzo;
    private javax.swing.JTextField txtSubtotalCena;
    private javax.swing.JTextField txtSubtotalDesayuno;
    private javax.swing.JTextField txtTotalCaloriasDia;
    // End of variables declaration//GEN-END:variables

    private void setEditable(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
